import type { ChangedFile, Finding } from "./types.js";

const dependencyFiles = new Set([
  "package.json",
  "package-lock.json",
  "pnpm-lock.yaml",
  "yarn.lock",
  "bun.lockb",
  "requirements.txt",
  "poetry.lock",
  "pyproject.toml",
  "Pipfile",
  "Pipfile.lock",
  "go.mod",
  "go.sum",
  "Cargo.toml",
  "Cargo.lock",
  "Gemfile",
  "Gemfile.lock"
]);

const sensitivePathPatterns = [
  /(^|\/)\.github\/workflows\//,
  /(^|\/)Dockerfile$/,
  /(^|\/)docker-compose\.ya?ml$/,
  /(^|\/)(auth|authentication|authorization|security|crypto|session|middleware)\b/i,
  /(^|\/)(rbac|acl|permissions?)\b/i,
  /(^|\/)(terraform|k8s|kubernetes|helm|infra)\//i,
  /(^|\/)\.env(\.|$)/i
];

const testPathPattern = /(^|\/)(__tests__|tests?|spec|e2e)\/|(\.|-)(test|spec)\.[cm]?[jt]sx?$/i;

const secretPatterns = [
  /AKIA[0-9A-Z]{16}/,
  /gh[pousr]_[A-Za-z0-9_]{20,}/,
  /xox[baprs]-[A-Za-z0-9-]{20,}/,
  /-----BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY-----/,
  /\b(api[_-]?key|secret|password|token)\b\s*[:=]\s*["'][^"']{12,}["']/i
];

const dangerousCodePatterns = [
  /\beval\s*\(/,
  /\bexec\s*\(/,
  /\bchild_process\.(exec|execSync|spawn|spawnSync)\b/,
  /\bshell\s*:\s*true\b/,
  /\bsubprocess\.(Popen|call|run)\(.*shell\s*=\s*True/i,
  /\binnerHTML\s*=/,
  /\bdocument\.write\s*\(/
];

export function analyzeRules(files: ChangedFile[]): Finding[] {
  const findings: Finding[] = [];
  const changedPaths = files.map((file) => file.path);
  const additions = files.reduce((sum, file) => sum + file.additions, 0);
  const deletions = files.reduce((sum, file) => sum + file.deletions, 0);
  const testFiles = files.filter((file) => testPathPattern.test(file.path));
  const nonTestFiles = files.filter((file) => !testPathPattern.test(file.path));

  const dependencyChanges = files.filter((file) => dependencyFiles.has(file.path.split("/").pop() ?? file.path));
  if (dependencyChanges.length > 0) {
    findings.push({
      ruleId: "dependency-change",
      title: "Dependency files changed",
      detail: "Dependency changes can introduce supply-chain, licensing, or build risks. Review package names and lockfile diffs carefully.",
      category: "dependency",
      level: dependencyChanges.length > 2 ? "high" : "medium",
      points: dependencyChanges.length > 2 ? 25 : 14,
      files: dependencyChanges.map((file) => file.path)
    });
  }

  const sensitiveFiles = files.filter((file) => sensitivePathPatterns.some((pattern) => pattern.test(file.path)));
  if (sensitiveFiles.length > 0) {
    findings.push({
      ruleId: "sensitive-area-change",
      title: "Security-sensitive files changed",
      detail: "The pull request touches CI, auth, secrets, infrastructure, containers, or security-related paths.",
      category: "security",
      level: "high",
      points: 24,
      files: sensitiveFiles.map((file) => file.path)
    });
  }

  const secretHits = files.filter((file) => secretPatterns.some((pattern) => pattern.test(file.patch ?? "")));
  if (secretHits.length > 0) {
    findings.push({
      ruleId: "possible-secret",
      title: "Possible secret detected in diff",
      detail: "A token, key, password, or private key-like value appears in added lines. Rotate the value if it is real.",
      category: "security",
      level: "critical",
      points: 45,
      files: secretHits.map((file) => file.path)
    });
  }

  const dangerousHits = files.filter((file) => dangerousCodePatterns.some((pattern) => pattern.test(file.patch ?? "")));
  if (dangerousHits.length > 0) {
    findings.push({
      ruleId: "dangerous-code-pattern",
      title: "Dangerous code pattern found",
      detail: "The diff includes patterns commonly associated with command execution, dynamic evaluation, or unsafe DOM writes.",
      category: "security",
      level: "high",
      points: 28,
      files: dangerousHits.map((file) => file.path)
    });
  }

  if (nonTestFiles.length >= 3 && testFiles.length === 0) {
    findings.push({
      ruleId: "missing-tests",
      title: "No test files changed",
      detail: "Multiple implementation files changed without any test or spec file updates.",
      category: "test-coverage",
      level: "medium",
      points: 16,
      files: nonTestFiles.slice(0, 8).map((file) => file.path)
    });
  }

  if (files.length >= 20 || additions + deletions >= 900) {
    findings.push({
      ruleId: "large-pr",
      title: "Large pull request",
      detail: "Large diffs are harder to review, especially when generated by an AI assistant. Consider splitting into smaller PRs.",
      category: "reviewability",
      level: additions + deletions >= 2000 ? "high" : "medium",
      points: additions + deletions >= 2000 ? 30 : 18,
      files: changedPaths.slice(0, 12)
    });
  }

  const generatedLikeFiles = files.filter((file) => {
    const patch = file.patch ?? "";
    return /generated by|auto-generated|do not edit/i.test(patch) || file.path.endsWith(".min.js");
  });
  if (generatedLikeFiles.length > 0) {
    findings.push({
      ruleId: "generated-output",
      title: "Generated output changed",
      detail: "Generated files can hide meaningful behavior changes. Verify the source change that produced them.",
      category: "maintainability",
      level: "medium",
      points: 12,
      files: generatedLikeFiles.map((file) => file.path)
    });
  }

  const ciFiles = files.filter((file) => /(^|\/)\.github\/workflows\/.+\.ya?ml$/.test(file.path));
  if (ciFiles.length > 0 && !changedPaths.some((path) => path.includes("README") || path.includes("docs/"))) {
    findings.push({
      ruleId: "ci-change-needs-context",
      title: "CI workflow changed without docs",
      detail: "CI changes should explain new permissions, triggers, secrets, or deployment behavior.",
      category: "ci",
      level: "medium",
      points: 10,
      files: ciFiles.map((file) => file.path)
    });
  }

  return findings.sort((a, b) => b.points - a.points);
}
